version: "3.7"

services:
  db:
    image: postgres:15.5
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: energy_bills
    ports:
      - "5432:5432"
    volumes:
      - energy-bills-db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"
    volumes:
      - pgadmin-config:/var/lib/pgadmin

volumes:
  energy-bills-db:
  pgadmin-config:
